# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190422_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
