# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190423_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30, verbose_name='w名称')),
                ('wage', models.IntegerField(verbose_name='w年龄')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Author')),
            ],
            options={
                'db_table': 'wife',
            },
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='网站'),
        ),
    ]
