# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=30)),
                ('uage', models.IntegerField()),
                ('uemail', models.CharField(max_length=200)),
            ],
        ),
    ]
