# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField()),
                ('logistics_company', models.IntegerField(choices=[(0, '圆通快递'), (1, '申通快递'), (2, '中通快递'), (3, '顺丰快递'), (4, 'EMS'), (5, '宅急送')], default=0, verbose_name='物流公司')),
                ('express_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='快递编号')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200, verbose_name='物流信息')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(default='abc', max_length=20, verbose_name='订单号')),
                ('ads', models.TextField(verbose_name='收货信息')),
                ('tomoney', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价格')),
                ('trmoney', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='实付价格')),
                ('amount', models.IntegerField(default=0, null=True, verbose_name='数量')),
                ('bank', models.CharField(default='unpay', max_length=50, verbose_name='支付方式加卡号')),
                ('dealtime', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('status', models.IntegerField(choices=[(0, '未付款'), (1, '等待发货'), (2, '配送中'), (3, '已完成'), (4, '支付失败'), (5, '已取消'), (6, '订单关闭')], default=0, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='商品名称', max_length=1000, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('desc', models.CharField(max_length=1000, null=True, verbose_name='描述')),
                ('amount', models.IntegerField(default=0, null=True, verbose_name='数量')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('spec', models.CharField(max_length=50, verbose_name='规格')),
                ('goodsimg', models.ImageField(default='normal.png', upload_to='ordersgood', verbose_name='产品图')),
                ('trprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品实际')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
