# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-26 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticsinfo',
            name='logist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Logistics'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
